
const members = [
  {
    name: "Aarohi Manchanda",
    position: "Convener Panel",
    team: "ECcc",
    behance:"",
    github:"https://github.com/aarohi309",
    linkedin:"https://www.linkedin.com/in/aarohi-manchanda",
    instagram:"https://www.instagram.com/aarohi_30/",
    image:
      "https://images.prismic.io/ieeemuj/a8ab29bc-44ef-433c-9a19-568ba74d4487_Slice+a.png?auto=compress,format",
  },
  {
    name: "Mahi Jain",
    position: "Convener Panel",
    team: "ECcc",
    behance:"",
    github:"https://github.com/mahijain21",
    linkedin:"https://www.linkedin.com/in/mahi-jain-1800a11a9",
    instagram:"https://www.instagram.com/_jain.mahi_",
    image:
      "https://images.prismic.io/ieeemuj/38e47866-1c20-4332-a387-649132f6701f_Slice+m+%281%29.png?auto=compress,format",
  },
  {
    name: "Mitesh Sharma",
    position: "Convener Panel",
    team: "ECcc",
    behance:"",
    github:"https://github.com/",
    linkedin:"",
    instagram:"test",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Manya Sharma",
    position: "Convener Panel",
    team: "ECcc",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"https://instagram.com/Manyasharma002",
    image:
      "https://images.prismic.io/ieeemuj/ab95d5f1-b19c-467a-88fc-a102a7555020_09D2C24B-1BF7-4949-A2FC-0FFF00CDBB50+-+MANYA+SHARMA.png?auto=compress,format&rect=0,0,96,96&w=96&h=96",
  },
  {
    name: "Aishwary Shree",
    position: "Convener Panel",
    team: "ECcc",
    behance:"test",
    github:"",
    linkedin:"test",
    instagram:"test",
    image:
      "https://images.prismic.io/ieeemuj/75bed82c-8b53-4b20-a4fa-92853856ec22_Aishwary+Shree_Chairperson.png?auto=compress,format",
  },
  {
    name: "Vaishnavi Parihar",
    position: "Convener Panel",
    team: "ECcc",
    behance:"",
    github:"",
    linkedin:"test",
    instagram:"test",
    image:
      "https://images.prismic.io/ieeemuj/76596942-6c4c-441f-aede-69b4aa446893_Vaishnavi+Parihar_Vice+Chairperson.png?auto=compress,format",
  },
  {
    name: "Vikramditya Hiran",
    position: "Events-EC",
    team: "EC",
    behance:"",
    github:"test",
    linkedin:"https://www.linkedin.com/in/vikramaditya-hiran-5502a3141/",
    instagram:"https://www.instagram.com/vikramaditya02_/",
    image:
      "https://images.prismic.io/ieeemuj/05dd3434-cefb-4dc3-bbe8-6f02b046f6dc_Slice+v.png?auto=compress,format",
  },
  {
    name: "Ritvik Chawla",
    position: "Events-EC",
    team: "EC",
    behance:"",
    github:"test",
    linkedin:"test",
    instagram:"test",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Rishav Agarwal",
    position: "Sponsorship-EC",
    team: "EC",
    behance:"",
    github:"",
    linkedin:"https://www.linkedin.com/in/rishav-agarwal-237857193",
    instagram:"https://instagram.com/rishavagarwal16?utm_medium=copy_link",
    image:
      "https://images.prismic.io/ieeemuj/fb78804e-1ae2-4d09-b562-4a3369907c28_Slice+r.png?auto=compress,format",
  },
  {
    name: "Utkarsh Rana",
    position: "Curations-EC",
    team: "EC",
    behance:"",
    github:"https://github.com/utkarshranaa",
    linkedin:"https://www.linkedin.com/in/utkarshranaa",
    instagram:"https://www.instagram.com/utkarshranaa/",
    image:
      "https://images.prismic.io/ieeemuj/3d2c6ba2-8654-4427-9e9a-092a12ece8ff_Slice+u.png?auto=compress,format",
  },
  {
    name: "Prayas Godara",
    position: "Marketing-EC",
    team: "EC",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Tanishaa Sinha",
    position: "Logistics-EC",
    team: "EC",
    behance:"",
    github:"https://github.com/tansinha-27",
    linkedin:"https://www.linkedin.com/in/archie-sharma-7412a31b7/",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/25216764-0553-4476-8b7a-dafc81665913_Tanishaa+Sinha_General+Secretary.png?auto=compress,format",
  },
  {
    name: "Archie Sharma",
    position: "Content-EC",
    team: "EC",
    behance:"",
    github:"",
    linkedin:"https://www.linkedin.com/in/archie-sharma-7412a31b7/",
    instagram:"https://www.linkedin.com/in/archie-sharma-7412a31b7/",
    image:
      "https://images.prismic.io/ieeemuj/2edd9ea1-206e-4d76-8848-d61975e5a479_Archie+Sharma_Treasurer.png?auto=compress,format",
  },
  {
    name: "Hardik Agarwal",
    position: "Finance-EC",
    team: "EC",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"https://www.instagram.com/_hardik_5_/",
    image:
      "https://images.prismic.io/ieeemuj/271c6083-be8c-4d1f-b1e9-bb0d5d067904_B1C32962-1700-418B-A97B-688F390BC0A5+-+Hardik+Agarwal.png?auto=compress,format&rect=0,0,96,96&w=96&h=96",
  },
  {
    name: "Yash Panchigar",
    position: "Hospitality-EC",
    team: "EC",
    behance:"",
    github:"https://github.com/Firestone99",
    linkedin:"https://instagram.com/rishavagarwal16?utm_medium=copy_link",
    instagram:"https://www.instagram.com/yash__pachchigar/",
    image:
      "https://images.prismic.io/ieeemuj/c82a6540-3f6a-4843-b7a9-6da75f4e4016_Slice+y.png?auto=compress,format&rect=0,0,150,150&w=96&h=96",
  },
  {
    name: "Jasjappan Singh",
    position: "Flying Squad-EC",
    team: "EC",
    behance:"https://www.behance.net/jappanj",
    github:"",
    linkedin:"https://www.linkedin.com/in/jasjappan-singh-a215a7140/",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/e01c8f4e-c1c1-4cd1-80f6-e368e09ce0b5_Jasjappan+Singh.png?auto=compress,format&rect=0,80,893,893&w=96&h=96",
  },
  {
    name: "Sejal Kothari",
    position: "Graphic Design-EC",
    team: "EC",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Suyash Patel",
    position: "Media-EC",
    team: "EC",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/bf1ef727-14c4-4b4f-aa33-3522ee86a065_Suyash+Patel.jpg?auto=compress,format",
  },
  {
    name: "Jeevanshi Bansal",
    position: "Crafts-EC",
    team: "EC",
    behance:"",
    github:"https://www.instagram.com/jeevu_11/",
    linkedin:"https://www.linkedin.com/in/jeevanshi-bansal-a6939a1b7/",
    instagram:"https://www.instagram.com/jeevu_11/",
    image:
      "https://images.prismic.io/ieeemuj/2dee38ff-7943-48e5-87e5-c8e0d0ce0d04_Jeevanshi+Bansal_Head+of+Operations+.png?auto=compress,format",
  },
  {
    name: "Aryan Kamnoj",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/3cdfb5ea-66fb-4c0d-8b5a-e4c20d442103_Aryan_+Joint+Community+manager+.jpeg?auto=compress,format",
  },
  {
    name: "Mehul Singhvi",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/6280e86c-751d-4e64-a2a1-4c8720613933_Mehul_Senior+Program+Coordinator+.webp?auto=compress,format",
  },
  {
    name: "Lokesh Kothari",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/b2363452-78c3-4709-ac77-76fa09a086db_LokesshKothari+SeniorProgramCoordinator.jpg?auto=compress,format",
  },
  {
    name: "Pratyaksh Singhal",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/0f4f4593-8bad-468f-9098-d057beee4924_Pratyaksh_senior+coordinator+of+corporate+affairs.jpg?auto=compress,format",
  },
  {
    name: "Divyansh Jain",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/800ec67a-d131-4c39-963a-99e4f9465df6_Divyansh+Jain_JointHeadOfLogistics.jpg?auto=compress,format",
  },
  {
    name: "Jitendra Choudhary",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/b54ad3f3-112c-4a15-abff-e6ab8c4b7093_Jitendra+Choudhary_Sr.+coordinator-Logistics.jpg?auto=compress,format",
  },
  {
    name: "Divya Srivastva",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/95a9edd9-981e-415f-8d37-e1e673b5a331_Divya+Joint+Head+of+Programs.jpg?auto=compress,format",
  },
  {
    name: "Rutuja Kadam",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/02c2a039-0b3e-4f29-a561-928ceab00599_RutujaKadam_SeniorPromotionsCoordinator.jpg?auto=compress,format",
  },
  {
    name: "Pravartika Mishra",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/8a328c04-dc53-4796-8b56-d849c95e0594_Pravartika_senior+community+manager.jpg?auto=compress,format",
  },
  {
    name: "Aastha",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/81f54ebd-c669-432c-a568-2b322221d03d_Aastha_senior+promotions+coordinate.jpg?auto=compress,format",
  },
  {
    name: "Shekhar Pilania",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/4cc855d9-00c2-4ff1-aee6-88aeaa717ad5_Shekhar_senior+program+coordinator.jpg?auto=compress,format",
  },
  {
    name: "Rajveer Sanghavi",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/1ed64a6e-b2dc-4534-a6be-88a73290840a_Rajveer_Sanghavi_SeniorProgramsCoordinator.jpg?auto=compress,format",
  },
  {
    name: "Rishabh Bassi",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/9b36e700-6aa5-433c-9572-e8092e07610e_Rishabhbass+Joint+head+of+graphic+design.jpeg?auto=compress,format",
  },
  {
    name: "Mahika Khanna",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/e04da226-b747-43aa-b9ed-9c821657bf34_Mahika+Khana.png?auto=compress,format",
  },
  {
    name: "Khushi Gupta",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Adeeb",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Anchal Tyagi",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/adefad2f-75f2-4550-87cf-374e8e5f4d87_Anchal+Tyagi_Head+of+Programs.png?auto=compress,format",
  },
  {
    name: "Sonakshi Arora",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/4eb05e48-274e-4eec-84d6-fc38975c41c6_Sonakshi+Arora_+Head+of+Technical+Projects.HEIC+%281%29.jpg?auto=compress,format",
  },
  {
    name: "Kshitij Malla",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/fc070c35-054e-4792-8198-28b4386bfb46_Kshiti+Malla_Joint+Head+of+Programs.png?auto=compress,format",
  },
  {
    name: "Aman Sethi",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Mohit Sinha",
    position: "Core Committee",
    team: "CCevents",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Aanchal Mittal",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/6f20e76c-4224-4a4f-92db-7b42a716449d_Aanchal+Mittal_Head+of+corporate+affairs.jpg?auto=compress,format",
  },
  {
    name: "Anish Kothari",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/e4a01a93-d850-4cf1-991f-d63d5893b20d_Anish+Kothari_+Senior+Editorial+Coordinator.jpg?auto=compress,format",
  },
  {
    name: "Vedika Parwal",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/cf1f2d7b-a033-442b-811d-24da175459c9_Vedika+Parwal_Joint+Head+Corporate+Affairs+.jpg?auto=compress,format",
  },
  {
    name: "Atul Raj Sharma",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/59f97e47-ff20-4c66-8306-90568ab88cbb_Atul+Raj+Sharma_+Head+of+Programs_.jpg?auto=compress,format",
  },
  {
    name: "Tanash Sultania",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/c70cc1fc-e15b-47ab-92fd-380730c2bcb6_Tanash+Sultania+_+senior+coordinator+of+curations_.jpg?auto=compress,format",
  },
  {
    name: "Vidit Parashar",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Yuvraj Vasudeva",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Arnav Rishi Raj",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Vanshika Singh Andotra",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/cc19b339-2dc1-46b2-ba86-bb44bdf05fa8_Vanshika+Singh+Andotra_Head+of+Curations.png?auto=compress,format",
  },
  {
    name: "Saloni Agrawal",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/fb494448-c461-45ec-9f2e-24b382a941c0_Saloni+Agrawal_Head+of+Editorial+.png?auto=compress,format",
  },
  {
    name: "Shriyanshi Srivastava",
    position: "Core Committee",
    team: "CCsponsorship",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/ef3b773e-f6c7-4b50-b57a-0853e3d442b0_Shriyanshi+Srivastava_Head+of+Corporate+Affairs+.png?auto=compress,format",
  },
  {
    name: "Aastha Gupta",
    position: "Core Committee",
    team: "CCcurations",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/4298c14f-4143-4efc-9e4d-b89c4683e52c_Aastha+Gupta_joint+head+of+curations.jpg?auto=compress,format",
  },
  {
    name: "Ishaan Gulrajani",
    position: "Core Committee",
    team: "CCcurations",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/59562f8c-bdb3-4aa4-a8e6-2acac0f49faa_Ishaan+Gulrajani_+Senior+Corporate+Affairs+Coordinator_.png?auto=compress,format",
  },
  {
    name: "Anant Sharma",
    position: "Core Committee",
    team: "CCcurations",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/0b444b12-2053-4932-8477-f04bf45b2c32_Anant+Sharma+_+senior+curations+coordinator.jpg?auto=compress,format",
  },
  {
    name: "Ridhi Makharia",
    position: "Core Committee",
    team: "CCcurations",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Anoushka Goyal",
    position: "Core Committee",
    team: "CCcurations",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Drishti Singh",
    position: "Core Committee",
    team: "CCcurations",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Manya Khater",
    position: "Core Committee",
    team: "CCcurations",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/9167f950-1b12-4714-b7e4-dff16824f3c4_Manya+Khater_Senior+Coordinator.png?auto=compress,format",
  },
  {
    name: "Kaushambika Chillar",
    position: "Core Committee",
    team: "CCcurations",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/0edf9f5d-dfd5-4c68-973e-ca1f9b19e354_Kaushambika+Chhillar_Senior+Coordinator.png?auto=compress,format",
  },
  {
    name: "Yoshe Vijay",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/cf654728-e6bd-4678-8a50-4b055b949326_Yoshe+Vijay+senior+social+media+coordinator+.jpg?auto=compress,format",
  },
  {
    name: "Sriansh Raj",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/5c96bb42-fab5-47ec-9d8f-6706468145dc_Sriansh+Raj_head+of+Promotions.png?auto=compress,format",
  },
  {
    name: "Yasir Tanveer",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/17727974-e4a0-4bd4-ad4e-8208154ba7b7_Yasir_social+media+senior+coordinator.jpg?auto=compress,format",
  },
  {
    name: "Aditya Pandey",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/cb2112fd-a2bf-4a2b-9999-3a3dc3f7402e_Aditya+Pandey_Joint+Head+of+Promotions.jpg?auto=compress,format",
  },
  {
    name: "Khushal Agarwal",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/3a39e812-b396-494b-935a-3449a4fd8580_Khushal+Agarwal_+Senior+Promotions+coordinator.jpg?auto=compress,format",
  },
  {
    name: "Samarth Bagga",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/1d1da31c-7c7a-4253-a97e-48d6ae399f97_Samarth+Bagga_senior+community+coordinator.jpeg?auto=compress,format",
  },
  {
    name: "Nayonika Sharma",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/bf9b56b6-9de8-4651-8999-95bc9a379b73_Nayonika+Sharma_Joint+Head+of+Social+Media.jpeg?auto=compress,format",
  },
  {
    name: "Anshi Sangani",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/ab4ac6c1-1caa-41e6-900b-2ab3da559567_ANSHI_head+of+social+media.png?auto=compress,format&rect=0,0,120,120&w=96&h=96",
  },
  {
    name: "Chahat Saluja",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Aditya Patil",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Aryaka",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Abhimanyu Bhasin",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/a77c300a-1a1c-480c-b438-c79c1fa031c7_Abhimanyu+Bhasin+_Senior+Coordinator.png?auto=compress,format",
  },
  {
    name: "Amisha Singh",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/ca6a5fc5-5881-4e10-8cf1-1b9ea66e4195_Amisha+Singh_Joint+Head+of+Promotions.png?auto=compress,format",
  },
  {
    name: "Veda Rathore",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/7b85638f-d383-4230-9eda-3aed96d4f63b_Veda+Rathod_Head+of+Promotions+.png?auto=compress,format",
  },
  {
    name: "Saloni Jain",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/5f46393a-53ea-4a1e-8f3c-79dad43aad12_Saloni+Jain_Senior+Coordinator.png?auto=compress,format",
  },
  {
    name: "Priya Singh",
    position: "Core Committee",
    team: "CCmarketing",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/df527b6c-9633-4747-bb7a-13d9ea27a152_Priya+Singh_Senior+Coordinator.png?auto=compress,format",
  },
  {
    name: "Nachiketa Jha",
    position: "Core Committee",
    team: "CClogistics",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/477e0a51-2aa7-49ef-bf36-acee774ff025_Nachiketa_HeadOfLogistics.jpg?auto=compress,format",
  },
  {
    name: "Pukhraj Singh",
    position: "Core Committee",
    team: "CClogistics",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/6d58b678-4cf2-4a60-b8aa-ebe87af4b67f_Pukhraj+Singh_Senior+Coordinator+Logistics.jpg?auto=compress,format",
  },
  {
    name: "Piyush Bansal",
    position: "Core Committee",
    team: "CClogistics",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/ba1e669d-a8a8-4d8c-a5a3-6c3fa3b886f2_Piyush+bansal_senior+logistics+coordinator.png?auto=compress,format",
  },
  {
    name: "Kartik Taneja",
    position: "Core Committee",
    team: "CClogistics",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/2cb3268e-3212-44b3-9638-1aee25e69474_KartikTaneja_Senior+Promotions+Coordinator.jpg?auto=compress,format",
  },
  {
    name: "Prakhar Goel",
    position: "Core Committee",
    team: "CClogistics",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Khushi Ganatra",
    position: "Core Committee",
    team: "CClogistics",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Maulik",
    position: "Core Committee",
    team: "CClogistics",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Rajveer Dhakani",
    position: "Core Committee",
    team: "CClogistics",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/36a88219-75d8-48c3-8fd5-d357880f3a26_Rajveer+Dhankani_Senior+Coordinator.png?auto=compress,format",
  },
  {
    name: "Anushka Saxena",
    position: "Core Committee",
    team: "CClogistics",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/ca40e126-f285-4ab2-9354-91cd6708b7d3_Anushka+Saxena_Head+of+Logistics.png?auto=compress,format",
  },
  {
    name: "Sonia Dighe",
    position: "Core Committee",
    team: "CCcontent",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/4dc0d0ee-5c96-4846-92e5-e9ee1e433c73_sonia+dighe-senior+editorial+coordinator_1.jpg?auto=compress,format",
  },
  {
    name: "Srivaishnavi",
    position: "Core Committee",
    team: "CCcontent",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/f7e98588-d456-4119-a98d-d2cf88dda2eb_Srivaishnavi_Joint-Head-of-Editorial.jpg?auto=compress,format",
  },
  {
    name: "Sanya Chaturvedi",
    position: "Core Committee",
    team: "CCcontent",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/fc774785-2eaf-45c8-8669-44b54a1d3f21_Sanya+Chaturvedi_Head+of+Editorial.jpg?auto=compress,format",
  },
  {
    name: "Avantika Yadav",
    position: "Core Committee",
    team: "CCcontent",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/072787e4-412b-423e-ae42-4e75c6e07369_Avantika_CommunityManager.jpg?auto=compress,format",
  },
  {
    name: "Mohd Asham",
    position: "Core Committee",
    team: "CCcontent",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Aditi Chandorkar",
    position: "Core Committee",
    team: "CCcontent",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/634a3c3a-7a2b-454d-96cf-cb6ecd595ec7_Aditi+Chandorkar_Senior+Coordinator+.png?auto=compress,format",
  },
  {
    name: "Chestha Vasudeva",
    position: "Core Committee",
    team: "CCcontent",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/00306655-2bc0-4b27-81de-e503e7c66a0c_Cheshtha+Vasudeva_Joint+Head+of+Editorial+.png?auto=compress,format",
  },
  {
    name: "Tanash Sultania",
    position: "Core Committee",
    team: "CCfinance",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/c70cc1fc-e15b-47ab-92fd-380730c2bcb6_Tanash+Sultania+_+senior+coordinator+of+curations_.jpg?auto=compress,format",
  },
  {
    name: "Lokesh Kothari",
    position: "Core Committee",
    team: "CCfinance",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/b2363452-78c3-4709-ac77-76fa09a086db_LokesshKothari+SeniorProgramCoordinator.jpg?auto=compress,format",
  },
  {
    name: "Jitendra Choudhary",
    position: "Core Committee",
    team: "CCfinance",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/b54ad3f3-112c-4a15-abff-e6ab8c4b7093_Jitendra+Choudhary_Sr.+coordinator-Logistics.jpg?auto=compress,format",
  },
  {
    name: "Dev Shalinkumar Agrawal",
    position: "Core Committee",
    team: "CCfinance",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Anish Ubriani",
    position: "Core Committee",
    team: "CCfinance",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Avanya Sagar",
    position: "Core Committee",
    team: "CCfinance",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/07a55261-4a73-403a-9292-19d35d187227_Avanya+Sagar_Joint+Head+Of+Media.png?auto=compress,format",
  },
  {
    name: "Anshi Sangani",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/ab4ac6c1-1caa-41e6-900b-2ab3da559567_ANSHI_head+of+social+media.png?auto=compress,format&rect=0,0,120,120&w=96&h=96",
  },
  {
    name: "Bhavya Bhardwaj",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/facf7f1b-ef9b-4ce3-8237-7e4e009568a3_Bhavya+Bhardwaj_Joint+head+of+media.jpg?auto=compress,format",
  },
  {
    name: "Avantika Yadav",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/072787e4-412b-423e-ae42-4e75c6e07369_Avantika_CommunityManager.jpg?auto=compress,format",
  },
  {
    name: "Pravartika Mishra",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/8a328c04-dc53-4796-8b56-d849c95e0594_Pravartika_senior+community+manager.jpg?auto=compress,format",
  },
  {
    name: "Aastha Gupta",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/4298c14f-4143-4efc-9e4d-b89c4683e52c_Aastha+Gupta_joint+head+of+curations.jpg?auto=compress,format",
  },
  {
    name: "Piyush Bansal",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/ba1e669d-a8a8-4d8c-a5a3-6c3fa3b886f2_Piyush+bansal_senior+logistics+coordinator.png?auto=compress,format",
  },
  {
    name: "Aditi Singh",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Ayush Tripathi",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Ankit Singh",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Vanisha Tyagi",
    position: "Core Committee",
    team: "CChospitality",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/d0b2e11b-2a3f-4f47-9efb-92547a675daf_VanishaTyagi_Head+Of+Social+Media.png?auto=compress,format",
  },
  {
    name: "Ishan Rai Agarwal",
    position: "Core Committee",
    team: "CCgraphicdesign",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/76227aad-0a64-431b-b6fd-5a531911331b_Ishan+Rai+Agarwal+senior+design+cordinator_.jpg?auto=compress,format",
  },

  {
    name: "Vyom",
    position: "Core Committee",
    team: "CCgraphicdesign",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/ff0eab8e-8b54-4398-929a-7315335aafef_Vyom+Agrawal+senior+graphic+design+coordinator+.JPG?auto=compress,format",
  },
  {
    name: "Mahika Khanna",
    position: "Core Committee",
    team: "CCgraphicdesign",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Rishabh Bassi",
    position: "Core Committee",
    team: "CCgraphicdesign",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/9b36e700-6aa5-433c-9572-e8092e07610e_Rishabhbass+Joint+head+of+graphic+design.jpeg?auto=compress,format",
  },
  {
    name: "Aman Singh",
    position: "Core Committee",
    team: "CCgraphicdesign",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Saket",
    position: "Core Committee",
    team: "CCgraphicdesign",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Pragya Prasad",
    position: "Core Committee",
    team: "CCgraphicdesign",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/d9728bc5-9ede-40bf-ab26-c8e3c401ffef_Pragya+Prasad_Head+of+Graphic+Design.png?auto=compress,format",
  },
  {
    name: "Tanay Srivastava",
    position: "Webmaster",
    team: "CCwebdev",
    behance:"",
    github:"https://www.instagram.com/tanay.srv/",
    linkedin:"https://www.linkedin.com/in/tanay-srivastava-92a11b1a6/",
    instagram:"https://www.instagram.com/tanay.srv/",
    image:
      "https://images.prismic.io/ieeemuj/1899323c-2ba1-44ed-b2d6-b2a0bdff6ef8_tanay_webmaster.jpg?auto=compress,format",
  },
  {
    name: "Somesh Kumar",
    team: "CCwebdev",
    behance:"",
    github:"https://www.instagram.com/kumarsomesh_unos/",
    linkedin:"https://www.linkedin.com/in/somesh-kumar-081a1022a/",
    instagram:"https://www.instagram.com/kumarsomesh_unos/",
    image:
      "https://images.prismic.io/ieeemuj/8df03deb-38a5-4b91-9878-e07a97809409_Somesh_DeputyWebmaster.JPG?auto=compress,format",
  },
  {
    name: "Sriansh Raj",
    position: "Core Committee",
    team: "CCflyingsquad",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/5c96bb42-fab5-47ec-9d8f-6706468145dc_Sriansh+Raj_head+of+Promotions.png?auto=compress,format",
  },
  {
    name: "Yasir Tanveer",
    position: "Core Committee",
    team: "CCflyingsquad",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/17727974-e4a0-4bd4-ad4e-8208154ba7b7_Yasir_social+media+senior+coordinator.jpg?auto=compress,format",
  },
  {
    name: "Aastha Tandon",
    position: "Core Committee",
    team: "CCflyingsquad",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/cdbd624e-ef95-4434-94e1-187a244b69ab_AasthaTandon_SeniorCoordinatorSocialMedia.jpg?auto=compress,format",
  },
  {
    name: "Anant Sharma",
    position: "Core Committee",
    team: "CCflyingsquad",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/0b444b12-2053-4932-8477-f04bf45b2c32_Anant+Sharma+_+senior+curations+coordinator.jpg?auto=compress,format",
  },
  {
    name: "Anjali",
    position: "Core Committee",
    team: "CCcrafts",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Nitya Shah",
    position: "Core Committee",
    team: "CCcrafts",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/240f2ff5-2c9b-4fd0-8fec-7f2865e1d837_Nitya+Shah_Senior+Coordinator.png?auto=compress,format",
  },
  {
    name: "Pukhraj Singh",
    position: "Core Committee",
    team: "CCcrafts",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/6d58b678-4cf2-4a60-b8aa-ebe87af4b67f_Pukhraj+Singh_Senior+Coordinator+Logistics.jpg?auto=compress,format",
  },
  {
    name: "Pravartika Mishra",
    position: "Core Committee",
    team: "CCcrafts",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/8a328c04-dc53-4796-8b56-d849c95e0594_Pravartika_senior+community+manager.jpg?auto=compress,format",
  },
  {
    name: "Suvijay Mahendru",
    position: "Core Committee",
    team: "CCmedia",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/28fe8a04-a9c8-43d2-b673-d1ef18c157ac_Suvijay_headofmedia.jpg?auto=compress,format",
  },
  {
    name: "Sanskar Singh",
    position: "Core Committee",
    team: "CCmedia",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/4ca4c7c0-5189-48e1-b0b0-9505d88581a3_Sanskar+singh_head+of+coverage.jpg?auto=compress,format",
  },
  {
    name: "Bhavya Bhardwaj",
    position: "Core Committee",
    team: "CCmedia",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://images.prismic.io/ieeemuj/facf7f1b-ef9b-4ce3-8237-7e4e009568a3_Bhavya+Bhardwaj_Joint+head+of+media.jpg?auto=compress,format",
  },
  {
    name: "Saksham Chaturvedi",
    position: "Core Committee",
    team: "CCmedia",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
  {
    name: "Shrrya Singh",
    position: "Core Committee",
    team: "CCmedia",
    behance:"",
    github:"",
    linkedin:"",
    instagram:"",
    image:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
  },
];

export default members;