const events = [
  {
    keys:"1",
    redirect: "11",
    image:
      "https://images.prismic.io/ieeemuj/5cb8ebc1-cd44-46c2-a04e-7d3c40571954_Ballistic+2.png?auto=compress,format  ",
    title: "Ballistic 2.0",
    desc: "Gaming competition between 2 teams. Games- Fifa 21 and Mortal Kombat",
    s_desc: "Gaming competition between 2 teams. Games- Fifa 21 and Mortal Kombat",
    dates: "7th-8th October",
    time: "7pm to 9pm",
    team_size: "2",
    prize: "",
    form: "",
    venue: "",
    form: "https://docs.google.com/forms/d/e/1FAIpQLSd_8Sz0OJAzEzBs596aivjtDYMzqEif-5VkZT-pxu6FulxQ6g",
  },
  {
    keys:"2",
    redirect: "22",
    image:
      "https://images.prismic.io/ieeemuj/36257aab-733a-4906-bff5-895bf0fdf1b0_Codeathon.png?auto=compress,format",
    title: "Code-a-thon",
    desc: "Overnight Codeathon in campus With multiple Problem Statements and the team should be able to solve all problems and run all the test cases successfully in the given Time.      There would also be interactive sessions in between to make it different and interesting.",
    s_desc:"Overnight Codeathon in campus With multiple Problem Statements and the team should be able to solve all problems",
    dates: "7th-8th October",
    time: "10:30pm to 6:00am",
    team_size: "1-3",
    prize: "Rs. 15,000",
    form: "https://docs.google.com/forms/d/e/1FAIpQLSco5xZWlOGdijka0Pyeyk-7-WdN98QoITyFT-FSRuGELTTPPg",
    venue: "10 rooms around 307 AB1",
  },
  {
    keys:"3",
    redirect: "33",
    image:
      "https://images.prismic.io/ieeemuj/717a62f9-86f5-49d7-9211-9e7f5d00eea3_Clone+the+App.png?auto=compress,format",
    title: "Clone the app",
    desc: "App Cloning competition, each team will be given an app(10 apps in total some will get the same app) and minimum functionalities (3) prior to the event. The teams have to make the app clones With the functionalities. On the day of the event the teams have to launch the app in front of a  panel of judges. The best clone fulfilling the functionalities wins.",
    s_desc:"App Cloning competition, each team will be given an app(10 apps in total some will get the same app)",
    dates: "8th October",
    time: "12pm to 3pm",
    team_size: "2-3",
    prize: "Rs. 10,000",
    form: "https://forms.gle/cCzmFh9w6pTwfsq69",
    venue: "4 classrooms around 101 AB1",
  },
  {
    keys:"4",
    redirect: "44",
    image:
      "https://images.prismic.io/ieeemuj/893ee826-2e4e-48db-b476-4e69f1ca022f_Breacout.png?auto=compress,format",
    title: "Breacout 3.0",
    desc: "This is a offline treasure hunt competition based on the theme of your two most beloved shows, friends and Brooklyn nine nine. With a common theme, participants will have a chance to choose which theme to go with. The first round will be an online quiz with not just questions from the show, but also dialogues, word searches etc. The qualified will have to team up with other contestants and form teams of 4 and will contest to become the champion in the treasure hunt which will happen in the campus",
    s_desc:"This is a offline treasure hunt competition based on the theme of your two most beloved shows, friends and Brooklyn nine nine.",
    dates: "8th October",
    time: "",
    team_size: "4",
    prize: "",
    form: "https://docs.google.com/forms/d/e/1FAIpQLSepiVqT5wAyzWTmUioPeyLr-Indbju6i9bAzBbfxLpacVLu_A",
    venue: "",
  },
  {
    keys:"5",
    redirect: "55",
    image:
      "https://images.prismic.io/ieeemuj/f4197dc3-a124-4923-bc95-81789f218a1b_Blogverse.png?auto=compress,format",
    title: "Blogverse",
    desc: "A contest to write a blog on provided specific core tech domains in a limited time and team/pair which completes in the shortest time will be awarded. After provision of clues regarding the topic, team will be provided with time slots for research, typing and presentation. Winners will be declared considering their performance in various domains.",
    s_desc: "A contest to write a blog on provided specific core tech domains in a limited time and team/pair which completes in the shortest time will be awarded. After provision of clues regarding the topic, team will be provided with time slots for research, typing and presentation.",
    dates: "8th October",
    time: "7:30pm to 10:00pm",
    team_size: "1-3",
    prize: "",
    form: "https://docs.google.com/forms/d/e/1FAIpQLScnbjWe8p4pfpsXcc2RLVxESPwfgkiyqnUcGh2mfM7frEtEAA",
    venue: "Room 307 AB1",
  },
  {
    keys:"6",
    redirect: "66",
    image:
      "https://images.prismic.io/ieeemuj/c30706a6-cc77-46fd-808a-47e4e592a613_Network+with+ieee.png?auto=compress,format",
    title: "Network With WIE ",
    desc: "A fun filled interaction session, to break the ice with fellow female engineers. The event will span throughout the nights, with games and interaction session with seniors.",
    s_desc: "A fun filled interaction session, to break the ice with fellow female engineers.",
    dates: "8th October",
    time: "11pm to 6am",
    team_size: "2",
    prize: "",
    form: "https://docs.google.com/forms/d/e/1FAIpQLSedm1Jz4caoSs32Jag6xelTD9f_U2MOvWIhSYG3Fz6U3Kyo2Q",
    venue: "",
  },
  {
    keys:"7",
    redirect: "77",
    image:
      "https://images.prismic.io/ieeemuj/919d1965-f305-43db-86ea-3e075cf4a869_Arduino.png?auto=compress,format",
    title: "Dron-acharya",
    desc: "Drone Building Workshop accompanied by drone flying.",
    s_desc: "Drone Building Workshop accompanied by drone flying.",
    dates: "9th October",
    time: "12pm to 4pm",
    team_size: "5-6",
    prize: "",
    form: "",
    venue: "",
  },
  {
    keys:"8",
    redirect: "88",
    image:
      "https://images.prismic.io/ieeemuj/acbb14f7-2e1a-41cf-92e6-155bd970c61e_Bug+Fixing.png?auto=compress,format",
    title: "ErrorTerror",
    desc: "Participants will be given a set of codes and they will have to Identify the errors in the code and rectify it to successfully run the code. It is time based so the fastest to debug wins.",
    s_desc: "Participants will be given a set of codes and they will have to Identify the errors in the code and rectify it to successfully run the code. It is time based so the fastest to debug wins.",
    dates: "9th October",
    time: "3pm to 5pm",
    team_size: "1",
    prize: "Rs. 10,000",
    form: "https://docs.google.com/forms/d/e/1FAIpQLSdwHhnGRiwEB_ApfKHnVaAWm89SdWwE30SQMTloyanqKczQPg",
    venue: "MS Teams",
  },
  {
    keys:"9",
    redirect: "99",
    image:
      "https://images.prismic.io/ieeemuj/888b8f3d-1411-4b88-88f3-06ff0a80867b_Tech+Summit.png?auto=compress,format",
    title: "Tech Summit",
    desc: "YouTubers, CEO and CTO of Web3.0(Blockchain, ML, Cybersecurity and Space exploration) based companies and scientists are gonna have a discussion of how is todays technology affect the future and talk about what the future holds in their respective domains.",
    s_desc: "YouTubers, CEO and CTO of Web3.0(Blockchain, ML, Cybersecurity and Space exploration) based companies and scientists are gonna have a discussion of how is todays technology affect the future and talk about what the future holds in their respective domains.",
    dates: "9th October",
    time: "4pm to 6pm",
    team_size: "",
    prize: "T shirts and Goodies for the best questions or interaction",
    form: "https://docs.google.com/forms/d/e/1FAIpQLSdaKlBniKpZjkgKlKA_AKtHmdGdqcp6YUTrN4fhca0o5Yd_CQ",
    venue: "TMA PAI AUDITORIUM",
  },
  ,
  {
    keys:"10",
    redirect: "111",
    image:
      "https://images.prismic.io/ieeemuj/6bb7e2e5-f232-4a73-be6f-fd55d76cd749_thebigshot.png?auto=compress,format",
    title: "Tech Talk",
    desc: "",
    s_desc: "",
    dates: "",
    time: "",
    team_size: "",
    prize: "",
    form: "https://docs.google.com/forms/d/e/1FAIpQLSefkBMpCSbBKhcrs50D3sBAykvoDeExNcjLmyo5QQr65QBfHg",
    venue: "",
  },
];
export default events;