import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import carousel from '../public/carousel/carousel.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GENISYS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.navbar}>
              <h2>GENISYS</h2>
              <ul>
                <li><Link href='#'><a>Platform</a></Link></li>
                <li><Link href='#'><a>Solutions</a></Link></li>
                <li><Link href='#'><a>Integrations</a></Link></li>
                <li><Link href='#'><a>Plans</a></Link></li>
                <li><Link href='#'><a>Resources</a></Link></li>
              </ul>
              <ul>
                  <li>Log-In</li>
                  <li>Sign-Up</li>
              </ul>
        </div>
        <div className={styles.carousel}>
          <Image 
            src={carousel}
            alt="Carousel image"
            priority>
          </Image>
          <h1>
            IEEE GENISYS '22
          </h1>
          <p>Manipal University, Jaipur</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
